export const Quotess = [
  "The best way to predict the future is to invent it. - Alan Kay                ",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll              ",
  "Your time is limited, so don't waste it living someone else's life. - Steve Jobs         ",
  "Winning isn’t everything, but wanting to win is. - Vince Lombardi         ",
  "I am not a product of my circumstances. I am a product of my decisions. - Stephen Covey         ",
  "Every child is an artist. The problem is how to remain an artist once he grows up. - Pablo Picasso         ",
  "You can never cross the ocean until you have the courage to lose sight of the shore. - Christopher Columbus         ",
  "The two most important days in your life are the day you are born and the day you find out why. - Mark Twain         ",
  "The best revenge is massive success. - Frank Sinatra         ",
  "You miss 100% of the shots you don’t take. - Wayne Gretzky         ",
  "Whether you think you can or you think you can’t, you’re right. - Henry Ford         ",
  "I have learned over the years that when one’s mind is made up, this diminishes fear. - Rosa Parks         ",
  "I alone cannot change the world, but I can cast a stone across the water to create many ripples. - Mother Teresa         ",
  "What we achieve inwardly will change outer reality. - Plutarch         ",
  "Believe you can and you're halfway there. - Theodore Roosevelt         ",
  "Start where you are. Use what you have. Do what you can. - Arthur Ashe         ",
  "Dream big and dare to fail. - Norman Vaughan         ",
  "Remember that not getting what you want is sometimes a wonderful stroke of luck. - Dalai Lama         ",
  "Too many of us are not living our dreams because we are living our fears. - Les Brown         ",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful. - Joshua J. Marine         ",
  "The only way to do great work is to love what you do. - Steve Jobs         ",
  "The best way out is always through. - Robert Frost         ",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis         ",
  "Happiness is not something ready made. It comes from your own actions. - Dalai Lama         ",
  "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer         ",
  "Your life does not get better by chance, it gets better by change. - Jim Rohn         ",
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. - Ralph Waldo Emerson         ",
  "To handle yourself, use your head; to handle others, use your heart. - Eleanor Roosevelt         ",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson         ",
  "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill         ",
  "The purpose of our lives is to be happy. - Dalai Lama         ",
  "Live as if you were to die tomorrow. Learn as if you were to live forever. - Mahatma Gandhi         ",
  "Life is what happens when you’re busy making other plans. - John Lennon         ",
  "Life is short, and it is up to you to make it sweet. - Sarah Louise Delany         ",
  "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman         ",
  "You have within you right now, everything you need to deal with whatever the world can throw at you. - Brian Tracy         ",
  "Believe you can and you’re halfway there. - Theodore Roosevelt         ",
  "May you live all the days of your life. - Jonathan Swift         ",
  "Life itself is the most wonderful fairy tale. - Hans Christian Andersen         ",
  "Do not let making a living prevent you from making a life. - John Wooden         ",
  "Life is ours to be spent, not to be saved. - D. H. Lawrence         ",
  "Keep smiling, because life is a beautiful thing and there's so much to smile about. - Marilyn Monroe         ",
  "Life is short, and it is up to you to make it sweet. - Sarah Louise Delany         ",
  "The longer I live, the more I realize the impact of attitude on life. - Charles R. Swindoll         ",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll         ",
  "Not how long, but how well you have lived is the main thing. - Seneca         ",
  "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost         ",
  "Life is made of ever so many partings welded together. - Charles Dickens         ",
  "Life is trying things to see if they work. - Ray Bradbury         ",
  "Your time is limited, so don’t waste it living someone else’s life. - Steve Jobs         ",
  "Don’t count the days, make the days count. - Muhammad Ali         ",
  "Good friends, good books, and a sleepy conscience: this is the ideal life. - Mark Twain         ",
  "Life would be tragic if it weren’t funny. - Stephen Hawking         ",
  "Live in the sunshine, swim the sea, drink the wild air. - Ralph Waldo Emerson         ",
  "The greatest pleasure of life is love. - Euripides         ",
  "Life is what happens when you’re busy making other plans. - John Lennon         ",
  "Life is really simple, but we insist on making it complicated. - Confucius         ",
  "Love the life you live. Live the life you love. - Bob Marley         ",
  "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well. - Ralph Waldo Emerson         ",
  "You have within you right now, everything you need to deal with whatever the world can throw at you. - Brian Tracy         ",
  "Life isn’t about finding yourself. Life is about creating yourself. - George Bernard Shaw         ",
  "Life is short, and truth works far and lives long: let us then speak the truth. - Arthur Schopenhauer         ",
  "Life is ten percent what happens to you and ninety percent how you respond to it. - Charles Swindoll         ",
  "Life is a flower of which love is the honey. - Victor Hugo         ",
  "Keep calm and carry on. - Winston Churchill         ",
  "Life is either a daring adventure or nothing at all. - Helen Keller         ",
  "The purpose of our lives is to be happy. - Dalai Lama         ",
  "Live in the sunshine, swim the sea, drink the wild air. - Ralph Waldo Emerson         ",
  "Life is short, and it is up to you to make it sweet. - Sarah Louise Delany         ",
  "The longer I live, the more I realize the impact of attitude on life. - Charles R. Swindoll         ",
  "You have within you right now, everything you need to deal with whatever the world can throw at you. - Brian Tracy         ",
  "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer         ",
  "Life is really simple, but we insist on making it complicated. - Confucius         ",
  "Do not let making a living prevent you from making a life. - John Wooden         ",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll         ",
  "Not how long, but how well you have lived is the main thing. - Seneca         ",
  "Believe you can and you’re halfway there. - Theodore Roosevelt         ",
  "Life is made of ever so many partings welded together. - Charles Dickens         ",
  "Life is trying things to see if they work. - Ray Bradbury         ",
  "Life itself is the most wonderful fairy tale. - Hans Christian Andersen         ",
  "You have within you right now, everything you need to deal with whatever the world can throw at you. - Brian Tracy         ",
  "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer         ",
  "The purpose of our lives is to be happy. - Dalai Lama         ",
  "Life is really simple, but we insist on making it complicated. - Confucius         ",
  "Do not let making a living prevent you from making a life. - John Wooden         ",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson         ",
  "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill         ",
  "Life itself is the most wonderful fairy tale. - Hans Christian Andersen         ",
  "Your time is limited, so don’t waste it living someone else’s life. - Steve Jobs         ",
  "Live in the sunshine, swim the sea, drink the wild air. - Ralph Waldo Emerson         ",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll         ",
  "Not how long, but how well you have lived is the main thing. - Seneca         ",
  "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost         ",
  "Life is made of ever so many partings welded together. - Charles Dickens         ",
  "Life is trying things to see if they work. - Ray Bradbury         ",
];
